In [15]:
import pandas as pd

# Ler o arquivo usando ponto e vírgula como separador
df = pd.read_csv('/content/Base Varejo.csv', sep=';')

# Mostrar as primeiras linhas
display(df.head())

# Diagnóstico da estrutura
print("Quantidade de registros:", df.shape[0])
print("Quantidade de colunas:", df.shape[1])

print("\nNomes das colunas:")
print(df.columns.tolist())

print("\nTipos de dados:")
print(df.dtypes)

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

Quantidade de registros: 830000
Quantidade de colunas: 14

Nomes das colunas:
['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG', 'PR_ID', 'PR_CAT', 'PR_NOME', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']

Tipos de dados:
DATA            object
CO_ID            int64
CL_ID            int64
CL_GENERO       object
CL_EC            int64
CL_FHL           int64
CL_SEG          object
PR_ID            int64
PR_CAT          object
PR_NOME         object
Unnamed: 10    float64
Unnamed: 11    float64
Unnamed: 12    float64
Unnamed: 13    float64
dtype: object

In [16]:
# 1. Verificar valores ausentes por coluna
print("VALORES AUSENTES POR COLUNA:")
print(df.isnull().sum())

# 2. Verificar textos vazios ou com apenas espaços
print("\nTEXTOS VAZIOS OU COM ESPAÇOS:")
for coluna in df.select_dtypes(include='object').columns:
    vazios = df[coluna].str.strip().eq('').sum()
    print(f"{coluna}: {vazios}")

# 3. Verificar linhas totalmente duplicadas
print("\nLINHAS DUPLICADAS:")
print("Total:", df.duplicated().sum())

# 4. Verificar as colunas extras
print("\nCOLUNAS EXTRAS:")
extras = [col for col in df.columns if col.startswith('Unnamed:')]
print(df[extras].isnull().sum())

# 5. Verificar os valores únicos das colunas textuais
print("\nVALORES ÚNICOS DAS COLUNAS TEXTUAIS:")
for coluna in df.select_dtypes(include='object').columns:
    print(f"\n{coluna}:")
    print(df[coluna].value_counts(dropna=False).head(10))

VALORES AUSENTES POR COLUNA:
DATA                0
CO_ID               0
CL_ID               0
CL_GENERO           0
CL_EC               0
CL_FHL              0
CL_SEG              0
PR_ID               0
PR_CAT              0
PR_NOME             0
Unnamed: 10    830000
Unnamed: 11    830000
Unnamed: 12    830000
Unnamed: 13    830000
dtype: int64

TEXTOS VAZIOS OU COM ESPAÇOS:
DATA: 0
CL_GENERO: 0
CL_SEG: 0
PR_CAT: 0
PR_NOME: 0

LINHAS DUPLICADAS:
Total: 96553

COLUNAS EXTRAS:
Unnamed: 10    830000
Unnamed: 11    830000
Unnamed: 12    830000
Unnamed: 13    830000
dtype: int64

VALORES ÚNICOS DAS COLUNAS TEXTUAIS:

DATA:
DATA
21/08/2020    4641
15/04/2019    4628
23/10/2021    4569
22/01/2022    4539
31/01/2022    4539
17/07/2022    4519
17/01/2021    4507
09/01/2020    4499
03/09/2021    4449
05/08/2022    4439
Name: count, dtype: int64

CL_GENERO:
CL_GENERO
F    432576
M    397424
Name: count, dtype: int64

CL_SEG:
CL_SEG
B    530163
C    232101
A     67736
Name: count, dtype: int64

PR_CAT:
PR_CAT
ALIMENTOS     434767
HIGIENE       155574
LIMPEZA       145754
BEBIDAS        43299
PET            32399
ACESSORIOS     14557
#N/D            3650
Name: count, dtype: int64

PR_NOME:
PR_NOME
PRESUNTO COZIDO       14381
SARDINHA               7490
GEL                    7399
BANANA                 7385
DESENGORDURANTE        7378
MODELADOR              7363
BIFE DE COXAO MOLE     7355
REMOVEDOR              7350
ESCOVA DE DENTE        7346
PAPINHA INFANTIL       7346
Name: count, dtype: int64

In [17]:
# Trabalhar com uma cópia para investigar a base
df_analise = df.copy()

# Remover somente as colunas totalmente vazias
colunas_vazias = df_analise.columns[
    df_analise.isnull().all()
].tolist()

df_analise = df_analise.drop(columns=colunas_vazias)

print("Colunas vazias identificadas:", colunas_vazias)
print("Colunas restantes:", df_analise.shape[1])

# Verificar exemplos de linhas duplicadas
duplicadas = df_analise[
    df_analise.duplicated(keep=False)
]

print("\nTotal de linhas envolvidas em duplicações:",
      len(duplicadas))

display(duplicadas.head(10))

# Investigar a categoria #N/D
print("\nRegistros com categoria #N/D:")
display(
    df_analise[df_analise["PR_CAT"] == "#N/D"].head(10)
)

# Conferir os valores de CL_FHL
print("\nValores de CL_FHL:")
print(df_analise["CL_FHL"].value_counts(dropna=False).sort_index())

Colunas vazias identificadas: ['Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']
Colunas restantes: 10

Total de linhas envolvidas em duplicações: 184330

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI
7,01/02/2019,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE
14,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA
15,01/02/2019,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE
19,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA
22,01/02/2019,1000,534,M,4,1,C,69,BEBIDAS,REFRIGERANTE LIMaO
34,01/02/2019,1000,534,M,4,1,C,225,ALIMENTOS,ATUM
40,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI
46,01/02/2019,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE
49,01/02/2019,1000,534,M,4,1,C,69,BEBIDAS,REFRIGERANTE LIMaO

Registros com categoria #N/D:

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
82,01/02/2019,1078,290,F,1,0,B,107,#N/D,#N/D
223,01/02/2019,1103,957,M,2,3,B,107,#N/D,#N/D
640,01/02/2019,1482,453,F,1,0,B,107,#N/D,#N/D
857,01/02/2019,1683,438,F,1,0,B,107,#N/D,#N/D
917,01/02/2019,1793,608,F,3,0,C,107,#N/D,#N/D
1185,01/02/2019,2151,493,M,2,4,B,107,#N/D,#N/D
1273,01/02/2019,2224,497,M,3,0,B,107,#N/D,#N/D
1303,01/02/2019,2311,164,M,2,3,A,107,#N/D,#N/D
1325,01/02/2019,2311,164,M,2,3,A,107,#N/D,#N/D
1385,01/02/2019,2327,689,M,2,0,C,107,#N/D,#N/D

Valores de CL_FHL:
CL_FHL
0    435501
1    102813
2    106622
3    104685
4     80379
Name: count, dtype: int64

In [18]:
# Verificar se os registros repetidos são idênticos
# considerando as colunas disponíveis

df_analise = df.drop(
    columns=[
        col for col in df.columns
        if col.startswith('Unnamed:')
    ]
).copy()

print("Total de registros:", len(df_analise))
print("Duplicatas exatas:", df_analise.duplicated().sum())

# Examinar um grupo de registros repetidos
exemplo = df_analise[
    df_analise.duplicated(keep=False)
]

display(exemplo.head(20))

# Verificar se há repetições da mesma combinação
# de data, compra, cliente e produto
chaves = ['DATA', 'CO_ID', 'CL_ID', 'PR_ID']

print("\nDuplicatas pela combinação de data, compra, cliente e produto:")
print(df_analise.duplicated(subset=chaves).sum())

# Verificar os registros do produto 107
print("\nRegistros do produto 107:")
display(
    df_analise[df_analise['PR_ID'] == 107]
    [['PR_ID', 'PR_CAT', 'PR_NOME']]
    .drop_duplicates()
)

Total de registros: 830000
Duplicatas exatas: 96553

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI
7,01/02/2019,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE
14,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA
15,01/02/2019,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE
19,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA
22,01/02/2019,1000,534,M,4,1,C,69,BEBIDAS,REFRIGERANTE LIMaO
34,01/02/2019,1000,534,M,4,1,C,225,ALIMENTOS,ATUM
40,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI
46,01/02/2019,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE
49,01/02/2019,1000,534,M,4,1,C,69,BEBIDAS,REFRIGERANTE LIMaO
50,01/02/2019,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE
51,01/02/2019,1000,534,M,4,1,C,225,ALIMENTOS,ATUM
68,01/02/2019,1078,290,F,1,0,B,144,BEBIDAS,REFRIGERANTE COLA
69,01/02/2019,1078,290,F,1,0,B,99,LIMPEZA,DESINFETANTE
70,01/02/2019,1078,290,F,1,0,B,23,ALIMENTOS,COGUMELOS
73,01/02/2019,1078,290,F,1,0,B,210,ACESSORIOS,CHUPETA
76,01/02/2019,1078,290,F,1,0,B,125,HIGIENE,TINTURAS
77,01/02/2019,1078,290,F,1,0,B,210,ACESSORIOS,CHUPETA
78,01/02/2019,1078,290,F,1,0,B,99,LIMPEZA,DESINFETANTE
79,01/02/2019,1078,290,F,1,0,B,156,HIGIENE,PASTA DE DENTE

Duplicatas pela combinação de data, compra, cliente e produto:
96553

Registros do produto 107:

    PR_ID PR_CAT PR_NOME
82    107   #N/D    #N/D

In [19]:
def tratar_dados(dados):

    """
    Remove colunas totalmente vazias e padroniza textos.
    Mantém duplicatas e categorias desconhecidas
    até haver evidência para removê-las.
    """
    dados = dados.copy()

    # Remover somente colunas completamente vazias
    dados = dados.dropna(axis=1, how='all')

    # Remover espaços extras e padronizar textos
    colunas_texto = dados.select_dtypes(
        include='object'
    ).columns

    for coluna in colunas_texto:
        dados[coluna] = dados[coluna].str.strip()

    # Padronizar nomes de produtos e categorias em maiúsculas
    for coluna in ['PR_CAT', 'PR_NOME', 'CL_GENERO', 'CL_SEG']:
        if coluna in dados.columns:
            dados[coluna] = dados[coluna].str.upper()

    return dados


# Aplicar a função
df_limpo = tratar_dados(df)

print("Registros antes:", len(df))
print("Registros depois:", len(df_limpo))
print("Colunas antes:", df.shape[1])
print("Colunas depois:", df_limpo.shape[1])
print("Duplicatas mantidas:", df_limpo.duplicated().sum())

Registros antes: 830000
Registros depois: 830000
Colunas antes: 14
Colunas depois: 10
Duplicatas mantidas: 96553

In [8]:
# Estatísticas básicas da coluna CL_FHL
coluna = 'CL_FHL'

print("Quantidade de valores válidos:", df_limpo[coluna].count())
print("Média:", df_limpo[coluna].mean())
print("Mínimo:", df_limpo[coluna].min())
print("Máximo:", df_limpo[coluna].max())

print("\nResumo estatístico completo:")
display(df_limpo[coluna].describe())

Quantidade de valores válidos: 830000
Média: 1.1465397590361446
Mínimo: 0
Máximo: 4

Resumo estatístico completo:

count    830000.00000
mean          1.14654
std           1.41696
min           0.00000
25%           0.00000
50%           0.00000
75%           2.00000
max           4.00000
Name: CL_FHL, dtype: float64

In [9]:
# FILTRO: selecionar registros da categoria ALIMENTOS
filtro_alimentos = df_limpo[
    df_limpo['PR_CAT'] == 'ALIMENTOS'
]

print("Registros da categoria ALIMENTOS:",
      len(filtro_alimentos))

# AGRUPAMENTO 1: quantidade de registros por categoria
print("\nQuantidade de registros por categoria:")
resumo_categoria = df_limpo.groupby(
    'PR_CAT'
).size().sort_values(ascending=False)

display(resumo_categoria)

# AGRUPAMENTO 2: quantidade de registros por gênero
print("\nQuantidade de registros por gênero:")
resumo_genero = df_limpo.groupby(
    'CL_GENERO'
).size().sort_values(ascending=False)

display(resumo_genero)

Registros da categoria ALIMENTOS: 434767

Quantidade de registros por categoria:

PR_CAT
ALIMENTOS     434767
HIGIENE       155574
LIMPEZA       145754
BEBIDAS        43299
PET            32399
ACESSORIOS     14557
#N/D            3650
dtype: int64

Quantidade de registros por gênero:

CL_GENERO
F    432576
M    397424
dtype: int64

In [20]:
# Quantidade de registros antes e depois da limpeza
print("Registros antes:", len(df))
print("Registros depois:", len(df_limpo))

# Conferir problemas restantes
print("\nValores ausentes por coluna:")
print(df_limpo.isnull().sum())

print("\nDuplicatas mantidas:")
print(df_limpo.duplicated().sum())

# Exportar a base tratada sem o índice
df_limpo.to_csv(
    '/content/varejo_limpo.csv',
    index=False,
    sep=';',
    encoding='utf-8-sig'
)

print("\nArquivo varejo_limpo.csv exportado com sucesso!")

Registros antes: 830000
Registros depois: 830000

Valores ausentes por coluna:
DATA         0
CO_ID        0
CL_ID        0
CL_GENERO    0
CL_EC        0
CL_FHL       0
CL_SEG       0
PR_ID        0
PR_CAT       0
PR_NOME      0
dtype: int64

Duplicatas mantidas:
96553

Arquivo varejo_limpo.csv exportado com sucesso!

In [21]:
from google.colab import files

files.download('/content/varejo_limpo.csv')

# Mini-Projeto de Análise de Dados com Python — Varejo

**Aluno:** Christiano Theiss  
**Turma:** T8  
**Disciplina:** Análise de Dados com Python  
**Módulo 1 — Semana 07**

## 1. Objetivo

Realizar uma Análise Exploratória de Dados (AED) de uma base de varejo utilizando Python e pandas, investigando a estrutura, a qualidade e as características dos registros. O projeto inclui diagnóstico, limpeza, estatísticas descritivas, filtros, agrupamentos e exportação de uma base tratada.

## 2. Origem dos dados

Base Varejo disponibilizada no Kaggle:

https://www.kaggle.com/datasets/namespaiva/base-varejo/data

**Arquivo utilizado:** `Base Varejo.csv`

**Formato:** CSV separado por ponto e vírgula (`;`).

## 3. Estrutura da base

A base original contém 830.000 registros e 14 colunas. Após a remoção de quatro colunas completamente vazias, restaram 830.000 registros e 10 colunas.

As colunas utilizadas são:

- `DATA`: data registrada.
- `CO_ID`: identificador associado à compra ou operação, conforme a estrutura da base.
- `CL_ID`: identificador do cliente.
- `CL_GENERO`: gênero registrado do cliente.
- `CL_EC`: variável cadastral do cliente; o significado exato deve ser confirmado na documentação da base.
- `CL_FHL`: variável numérica do cliente, com valores de 0 a 4; o significado exato deve ser confirmado.
- `CL_SEG`: segmento do cliente.
- `PR_ID`: identificador do produto.
- `PR_CAT`: categoria do produto.
- `PR_NOME`: nome do produto.

A unidade de análise adotada é o registro da base. Portanto, as contagens apresentadas não devem ser interpretadas automaticamente como clientes únicos, compras únicas ou faturamento.

## 4. Diagnóstico e decisões de limpeza

O diagnóstico inicial identificou:

- 830.000 registros.
- Nenhum valor ausente nas dez colunas principais.
- Quatro colunas extras (`Unnamed: 10` a `Unnamed: 13`) completamente vazias.
- Nenhum texto vazio ou composto apenas por espaços nas colunas textuais verificadas.
- 96.553 linhas duplicadas exatas.
- 3.650 registros com `#N/D` nas categorias de produto.

As quatro colunas totalmente vazias foram removidas. Os textos das colunas categóricas foram padronizados com remoção de espaços nas extremidades e conversão para maiúsculas.

As linhas duplicadas foram mantidas, pois a base não possui uma coluna de quantidade que permita distinguir com segurança uma repetição indevida de itens repetidos em uma compra. O valor `#N/D` também foi mantido, pois não há documentação suficiente para determinar se deve ser convertido em valor ausente ou excluído.

## 5. Processo de tratamento

A leitura da base foi realizada com `pd.read_csv()`, utilizando `sep=';'` para separar corretamente as colunas. A transformação foi implementada na função `tratar_dados()`, que remove colunas totalmente vazias e padroniza textos. A função `gerar_resumo()` foi utilizada para produzir resumos categóricos.

A base tratada foi exportada para `varejo_limpo.csv`, sem índice, usando `index=False`. A limpeza removeu quatro colunas sem informação, mas preservou os 830.000 registros, evitando exclusões sem justificativa.

## 6. Resultados e conclusões

- A base possui 830.000 registros e 10 colunas úteis após a remoção das quatro colunas vazias.
- A categoria `ALIMENTOS` apresenta 434.767 registros, aproximadamente 52,4% do total.
- A categoria `HIGIENE` apresenta 155.574 registros, seguida por `LIMPEZA`, com 145.754.
- Os registros associados ao gênero `F` somam 432.576, enquanto os associados a `M` somam 397.424.
- A variável `CL_FHL` apresenta 830.000 valores válidos, média de aproximadamente 1,1465, mínimo 0 e máximo 4.
- Foram encontradas 96.553 linhas duplicadas exatas e 3.650 registros com `#N/D`. Esses casos foram mantidos para evitar exclusões sem evidência suficiente.

**Recomendação:** investigar a predominância da categoria `ALIMENTOS` e verificar, junto ao responsável pela base, o significado dos campos cadastrais e dos registros `#N/D` antes de tomar decisões comerciais.

**Limitação:** a base não apresenta valores de venda ou quantidades explícitas. Por isso, esta análise não permite calcular faturamento nem afirmar que a contagem de registros corresponde ao número de compras ou clientes únicos.

## 7. Como executar

1. Abra o Google Colab.
2. Envie o arquivo original `Base Varejo.csv`.
3. Execute as células do notebook na ordem, desde a importação até a exportação.
4. Confira se o arquivo `varejo_limpo.csv` foi gerado.
5. Consulte o notebook para verificar os diagnósticos, as funções e os resultados.

## 8. Arquivos do projeto

- `Miniprojeto_Christiano_Theiss_T8.ipynb`: notebook com código, diagnósticos e análises.
- `Base Varejo.csv`: base original utilizada.
- `varejo_limpo.csv`: base tratada e exportada.
- `README.md`: documentação, decisões e conclusões.

In [13]:
import gzip
import shutil

with open('/content/varejo_limpo.csv', 'rb') as original:
    with gzip.open('/content/varejo_limpo.csv.gz', 'wb') as comprimido:
        shutil.copyfileobj(original, comprimido)

In [14]:
from google.colab import files

files.download('/content/varejo_limpo.csv.gz')